#! /bin/sh

#
# 启动sxhkd
#
pgrep -x sxhkd >/dev/null || sxhkd &

#
# 设置正确的屏幕顺序
# 脚本由arandr程序自动生成,并保存在bspwm的scripts目录下的
# https://blog.csdn.net/lxyoucan/article/details/124794123
#
$HOME/.config/bspwm/scripts/screen-order.sh &

#
# 设置鼠标样式，默认为X号
xsetroot -cursor_name left_ptr

#
# 设置壁纸
# 用一个小脚本每2m设置一下就好
#

$HOME/.config/bspwm/scripts/auto-change-wallpapers.sh &

# cairo-dock
#

#$HOME/.config/bspwm/scripts/cairo-dock.sh &

#
# 启动polybar
# polybar-themes
# https://github.com/adi1090x/polybar-themes
# 也可以paru 安装polybar-themes-git
~/.config/polybar/launch.sh --forest

# polybar-collection
# https://github.com/Murzchnvok/polybar-collection
#$HOME/polybar-collection/launch.sh
#$HOME/.config/polybar/polybar-collection/launch.sh

#
# 启动网络托盘
#nm-applet &

# 
# 启动xfce4-panel
#
xfce4-panel &
# 避免重叠
bspc config top_padding 24

#
# 启动蓝牙系统托盘
#blueman-applet &

#
# 启动volctl音量托盘
#volctl &

#
# 启动麦克风系统托盘
#mictray &

#
# 启动数字小键盘
numlockx on

#
# 启动picom窗口合成器
picom &

#
# 启动fcitx5
fcitx5 &

#
# 启动jetbrains-toolbox
# xfce4-panel中可以自动显示他,toolbox中有随系统开启启动选项,这里如果再运行一遍,开机后会弹出窗口
# jetbrains-toolbox &
$HOME/.config/bspwm/scripts/start_jetbrains_toolbox.sh &


#
# 启动坚果云
# 改为在脚本中启用，这样就不用每次开启就弹窗口了
#nutstore &
$HOME/.config/bspwm/scripts/start_nutstore.sh &

#
# U盘自动挂载
# 参考https://zhuanlan.zhihu.com/p/568211941
udiskie &

# 启动xdman下载工具
# 依然改为在.xinitrc中启动

#xdman &
#
#
#
#

########################## Single monitor #####################
##########################    单显示器    #####################
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

########################## 双显示器设置  #######################

######################### 方法1 ###############################
# 双显示器设置,受启发于archwiki中bspwm下面的推荐连接
# https://github.com/windelicato/dotfiles
#
#注意：受启发于https://github.com/polybar/polybar/issues/763
#在polybar中也要设置多显示器显示
#i = 1
#for monitor in $(bspc query -M); do
#bspc monitor $monitor -n "$i" -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
#	let i++
#done

####################### 方法2 #################################
# 参考资料https://www.bilibili.com/video/BV1dB4y1w7FB/?spm_id_from=333.999.0.0
# https://github.com/arcolinux/arcolinux-bspwm/blob/master/etc/skel/.config/bspwm/bspwmrc
# 使用xrandr 查找显示器名字
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

# 全部十个标签
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 10
#
# 俩都10个太多了,用不过来
#bspc monitor DP-2 -d 1 2 3 4 5
#bspc monitor DP-4 -d 6 7 8 9 10

# 24 + 27
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-0 -d 6 7 8 9 10
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
# 笔记本外接显示器
# bspc monitor eDP-1-1 -d 1 2 3 4 5
#bspc monitor DP-2 -d 1 2 3 4 5
#bspc monitor HDMI-0 -d 6 7 8 9 10
# bspc monitor DP-2 -d 6 7 8 9 10
#
# Visual options
# 可视化参数
# 参数通过man bspwm获得
bspc config border_width 2
bspc config window_gap 12
bspc config focused_border_color \#00FF00
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
#
# 鼠标相关设置新版本在bspwmrc中设置而不在sxhkd中里https://www.reddit.com/r/bspwm/comments/6pdirx/unknown_domain_or_command_pointer/
# 参考自https://github.com/gh0stzk/dotfiles/blob/master/config/bspwm/bspwmrc
# 相关参数 能够接受的值在man bspwm中有
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
#bspc config pointer_motion_interval       5
#bspc config pointer_modifier              mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#
# Rules
# 规则
#

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# plank始终置顶设置,受chatgpt启发
# bspwm窗口通常被放置在桌面的顶部,这里设置plank始终放在其他窗口最上方
# xprop | grep WM_CLASS测出来的名字
#bspc rule -a Plank state=floating sticky=on layer=above
#
# 启动plank
# 利用脚本方法,防止plank被窗口遮挡
#sleep 10
#sleep 5s && plank -n prim &
#$HOME/.config/bspwm/scripts/plank.sh &
