#!/bin/bash

# 保存当前的环境变量
OLD_QT_SCALE_FACTOR=$QT_SCALE_FACTOR
OLD_QT_AUTO_SCREEN_SCALE_FACTOR=$QT_AUTO_SCREEN_SCALE_FACTOR
OLD_QT_SCREEN_SCALE_FACTORS=$QT_SCREEN_SCALE_FACTORS
OLD_QT_FONT_DPI=$QT_FONT_DPI
OLD_QT_ENABLE_HIGHDPI_SCALING=$QT_ENABLE_HIGHDPI_SCALING
OLD_QT_USE_PHYSICAL_DPI=$QT_USE_PHYSICAL_DPI

# 临时设置 Flameshot 的缩放
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export QT_SCREEN_SCALE_FACTORS=1
unset QT_FONT_DPI
unset QT_ENABLE_HIGHDPI_SCALING
unset QT_USE_PHYSICAL_DPI

# 启动 Flameshot
flameshot gui "$@"

# 恢复原来的环境变量
export QT_SCALE_FACTOR=$OLD_QT_SCALE_FACTOR
export QT_AUTO_SCREEN_SCALE_FACTOR=$OLD_QT_AUTO_SCREEN_SCALE_FACTOR
export QT_SCREEN_SCALE_FACTORS=$OLD_QT_SCREEN_SCALE_FACTORS
export QT_FONT_DPI=$OLD_QT_FONT_DPI
export QT_ENABLE_HIGHDPI_SCALING=$OLD_QT_ENABLE_HIGHDPI_SCALING
export QT_USE_PHYSICAL_DPI=$OLD_QT_USE_PHYSICAL_DPI
